add validate-service-mesh job
openinfradev/hanu-ci-jobs pull request #17
Opened 2021-03-25 07:24 UTC by robertchoi80

service-mesh infra (istiod 및 ingressGateway) 배포 후 정상 동작하는지 검증하기 위한 job. 
Sample app 및 관련 virtualService 를 생성하고, 실제로 ingressUrl을 통해 접속 가능한지 검증하는 내용임.

2021-03-25 08:32 UTC, jabbukka requested changes

2021-03-25 08:32 UTC, jabbukka commented on validate-service-mesh/Jenkinsfile
> +          sh "curl -s -I -HHost:nginx.hanu.com http://${endpoint}:${ingressNodePort}"
Debug라고 되어있는데 삭제되어야 하는 거 아닐까요?

2021-03-25 09:06 UTC, robertchoi80 commented on validate-service-mesh/Jenkinsfile
> +          sh "curl -s -I -HHost:nginx.hanu.com http://${endpoint}:${ingressNodePort}"
아 요거 아직 테스트를 못해봐서, 실제로 job 돌려보고 잘 되면 그때 지우려 합니다. 첨부터 리턴 코드만 검사하면 뭔가 에러 났을 때 왜 안됐는지 판단히 안될듯 해서요..  TODO 주석 추가해서 다시 올렸습니다.

2021-04-02 00:31 UTC, jabbukka approved these changes

2021-04-28 02:52 UTC, merged