Jenkins Pipeline to check slack alarm fired
openinfradev/hanu-ci-jobs pull request #20
Opened 2021-05-20 12:44 UTC by seungkyua

[ ] prometheus node exporter 가 다운되었을 경우 sample alert 를 발생하는 prometheus rule 을 추가
[ ] prometheus node exporter 삭제
[ ] 1. alertmanager 로 alert 리스트를 쿼리
     2. slack #temporary-alert 채널에서 message 쿼리
     3. 둘이 비교하여 alert 와 slack 발생 메세지가 같으면 alert 성공
[ ] prometheus node exporter 생성

2021-05-21 01:17 UTC, zugwan requested changes

2021-05-21 01:17 UTC, zugwan commented on validate-lma/Jenkinsfile
> +          patchJson = " \\\"{\\\\\\\"spec\\\\\\\": {\\\\\\\"values\\\\\\\": {\\\\\\\"alertmanager\\\\\\\": {\\\\\\\"config\\\\\\\": {\\\\\\\"global\\\\\\\": {\\\\\\\"slack_api_url\\\\\\\": \\\\\\\"${
SLACK_API_URL 파라미터 정의 부분이 누락되어 있습니다.

2021-05-21 01:17 UTC, zugwan commented on validate-lma/Jenkinsfile
> +              validate-lma/check_alert.py ${amUrl} ${params.SLACK_BOT_TOKEN}
SLACK_BOT_TOKEN 파라미터 정의 부분이 누락되어 있습니다.

2021-05-21 02:11 UTC, seungkyua commented on validate-lma/Jenkinsfile
> +          patchJson = " \\\"{\\\\\\\"spec\\\\\\\": {\\\\\\\"values\\\\\\\": {\\\\\\\"alertmanager\\\\\\\": {\\\\\\\"config\\\\\\\": {\\\\\\\"global\\\\\\\": {\\\\\\\"slack_api_url\\\\\\\": \\\\\\\"${
Jenkins Job Config 에서 넣어 줘야 합니다. 여기에 null 로 정의를 하게 되면 돌릴 때 값이 초기화되서 매번 넣어줘야 합니다. github 에 저장하는 순간 값은 invalid 됩니다. 그래서 여기에 정의하지 않았어요.

2021-05-21 02:11 UTC, seungkyua commented on validate-lma/Jenkinsfile
> +              validate-lma/check_alert.py ${amUrl} ${params.SLACK_BOT_TOKEN}
Jenkins Job Config 에서 넣어 줘야 합니다. 여기에 null 로 정의를 하게 되면 돌릴 때 값이 초기화되서 매번 넣어줘야 합니다. github 에 저장하는 순간 값은 invalid 됩니다. 그래서 여기에 정의하지 않았어요.

2021-05-21 02:21 UTC, zugwan commented on validate-lma/Jenkinsfile
> +          patchJson = " \\\"{\\\\\\\"spec\\\\\\\": {\\\\\\\"values\\\\\\\": {\\\\\\\"alertmanager\\\\\\\": {\\\\\\\"config\\\\\\\": {\\\\\\\"global\\\\\\\": {\\\\\\\"slack_api_url\\\\\\\": \\\\\\\"${
네, 이해했습니다.

2021-05-21 02:21 UTC, zugwan commented on validate-lma/Jenkinsfile
> +              validate-lma/check_alert.py ${amUrl} ${params.SLACK_BOT_TOKEN}
네, 이해했습니다.

2021-05-21 02:22 UTC, zugwan approved these changes

2021-05-21 03:07 UTC, intelliguy requested changes

2021-05-21 03:07 UTC, intelliguy commented on validate-lma/Jenkinsfile
> +            ssh -o StrictHostKeyChecking=no -i /opt/jenkins/.ssh/jenkins-slave-hanukey root@${endpoint} "kubectl patch hr prometheus-fed-master --type=merge -p ${patchJson}"
여기와 아래에서 배포된 내용을 변경시키는 설정들이 있는데 복구시켜주는 로직이 없습니다.
확인부탁드립니다.

2021-05-21 03:13 UTC, intelliguy commented on validate-lma/Jenkinsfile
> +              validate-lma/check_alert.py ${amUrl} ${params.SLACK_BOT_TOKEN}
python 문자열에서도 invalid 시키나요?
python에서 해당 값을 전달하지 않으면 default로 기본값 처리해도 될꺼 같은데.

2021-05-21 03:13 UTC, seungkyua commented on validate-lma/Jenkinsfile
> +            ssh -o StrictHostKeyChecking=no -i /opt/jenkins/.ssh/jenkins-slave-hanukey root@${endpoint} "kubectl patch hr prometheus-fed-master --type=merge -p ${patchJson}"
slack_api_url 은 jenkins job 의 conf 에서 받은 slack 호출을 위한 url 입니다. 오히려 제대로 세팅을 해야 하는 부분으로 복구 하지 않습니다.

2021-05-21 06:33 UTC, seungkyua commented on validate-lma/Jenkinsfile
> +            ssh -o StrictHostKeyChecking=no -i /opt/jenkins/.ssh/jenkins-slave-hanukey root@${endpoint} "kubectl patch hr prometheus-fed-master --type=merge -p ${patchJson}"
alert config 는 삭제하는 것으로 수정했습니다.

2021-06-08 03:54 UTC, zugwan approved these changes

2021-06-11 01:42 UTC, intelliguy approved these changes

2021-06-11 01:42 UTC, merged