add validate-lma jenkins job
openinfradev/hanu-ci-jobs pull request #4
Opened 2021-02-18 07:36 UTC by jabbukka

* lma를 검증하는 Jenkins job입니다.
* 현재는 efk만 작업하였지만 이후 다른 테스트도 함께 추가하면 될것같습니다.

2021-02-18 09:39 UTC, jabbukka commented
성공한 Jenkins job 링크 입니다. https://jenkins.hanu-ci.io/job/validate-lma/6/console

2021-02-18 11:29 UTC, zugwan requested changes

2021-02-18 11:29 UTC, zugwan commented on validate-lma/Jenkinsfile
> +            #rm -rf /var/lib/jenkins/.ssh/known_hosts
삭제하는 것이 좋을 듯 합니다.

2021-02-18 11:29 UTC, zugwan commented on validate-lma/Jenkinsfile
> +            cp /opt/jenkins/.ssh/jenkins-slave-hanukey ./jenkins.key
아래 ssh 명령어에서 '/opt/jenkins/.ssh/jenkins-slave-hanukey' 경로로 바로 키를 사용하지 않고 복사해서 사용해야 하는 이유가 있을까요?

2021-02-18 23:58 UTC, jabbukka commented on validate-lma/Jenkinsfile
> +            #rm -rf /var/lib/jenkins/.ssh/known_hosts
삭제하였습니다.

2021-02-19 00:03 UTC, jabbukka commented on validate-lma/Jenkinsfile
> +            cp /opt/jenkins/.ssh/jenkins-slave-hanukey ./jenkins.key
validate-k8s job을 복사, 수정하여 만들며 똑같이 사용한 문구인데, 특별한 이유는 없는 것 같아 /opt/ 밑의 key를 직접사용하도록 변경하였습니다.

2021-02-19 00:13 UTC, zugwan approved these changes

2021-02-19 00:13 UTC, merged