TACODEV-668: add test for the prometheus server and relatives
openinfradev/hanu-ci-jobs pull request #7
Opened 2021-02-23 04:29 UTC by intelliguy

Prometheus에 대한 검증 job 수행

### Prometheus and exporters.
TACO LMA를 설치하면 다음과 같은 챠트들이 기본으로 배포된다.
* Prometheus Server류
  * prometheus
  * prometheus-fed-master
  * thanos
* Exporter 류
  * prometheus-node-exporter
  * kube-state-metrics
  * kubernetes-event-exporter 
* 기본 컴포넌트
  * prometheus-operator
  * prometheus-process-exporter
  * prometheus-pushgateway
  * prometheus-adapter

다단계의 Pipeline을 거쳐서 궁극적으로는 fed-master나 thnos를 통해 그 값을 조회하게 되면 모든 컴포넌트가 잘 설치되었음을 확인할 수 있다.
추가적으로 위에서 보여지는 내용외에도 Prometheus는 내부적으로 준비된 다양한 데이터 소스에서 매트릭을 수집하게 되는데 이를 나열하면 다음과 같다.
다만 이 내용은 현재(2021.02)의 형상을 담고 있으므로 지속적으로 prometheus 진영과 Ha.nu의 LMA 변경사항을 반영해 줘야한다.

Scrap Target
* kubernetes
* kube-state-metrics
* lma-coredns
* lma-kube-controller-manager
* lma-kube-proxy
* lma-kube-scheduler
* lma-prometheus
* process-exporter
* prometheus-node-exporter
* prometheus-operator-kube-p-kubelet
* prometheus-operator-kube-p-operator
* prometheus-pushgateway
* prometheus-test-kube-prome-kubelet

각 Target의 up 메트릭을 조회하여 합을 구한것이 0보다 크다면 다음의 내역을 확인할 수 있다.
1. target별 exporter가 정상동작 중
2. exporter의 데이터를 prometheus 서버에서 잘 수취하고 저장함
3. prometheus 서버에 대한 promQL이 잘 처리되어 정확한 동작을 수행함

2021-02-23 04:49 UTC, jabbukka requested changes

2021-02-23 04:49 UTC, jabbukka commented on validate-lma/check_prometheus.py
> +url = "http://192.168.5.61:30008/api/v1/query"
url을 parameter로 받아와야 할 것 같습니다.

2021-02-23 04:53 UTC, intelliguy commented on validate-lma/check_prometheus.py
> +url = "http://192.168.5.61:30008/api/v1/query"
Thanks

2021-02-23 05:14 UTC, zugwan commented on validate-lma/README.md
> +다단계의 Pipeline을 거쳐서 궁극적으로는 fed-master나 thnos를 통해 그 값을 조회하게 되면 모든 컴포넌트가 잘 설치되었음을 확인할 수 있다.
thnos 오타 입니다. -> thanos

2021-02-23 06:18 UTC, jabbukka approved these changes

2021-02-24 02:51 UTC, zugwan approved these changes

2021-02-24 02:51 UTC, merged